### ISSUE TITLE
debian7.7执行GouYong报错：TypeError: new() takes exactly 1 argument (0 given)

### ISSUE THREAD

**Issue by suker413** [jiffies/GouYong#3]
liangsh@lsh-dev:~/Downloads/marisa-0.2.4$ GouYong 
[INFO 2015-01-19 19:14:23,541 youdaoQuery]:cache folder exists.
Traceback (most recent call last):
  File "/usr/local/bin/GouYong", line 9, in <module>
    load_entry_point('GouYong==0.3', 'gui_scripts', 'GouYong')()
  File "/usr/local/lib/python2.7/dist-packages/GouYong-0.3-py2.7.egg/GouYong/src/window.py", line 256, in main
    pop=Popup()
  File "/usr/local/lib/python2.7/dist-packages/GouYong-0.3-py2.7.egg/GouYong/src/window.py", line 32, in __init__
    self.init_textview()
  File "/usr/local/lib/python2.7/dist-packages/GouYong-0.3-py2.7.egg/GouYong/src/window.py", line 36, in init_textview
    self.textbuffer = Gtk.TextBuffer.new()
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 72, in constructor
    return info.invoke(cls, *args, **kwargs)
TypeError: new() takes exactly 1 argument (0 given)

**Comment by jiffies** [comment]
谢谢测试，已修正，不过launchpad软件源还要以后更新，你可以git clone到本地，然后运行python GouYong/src/window.py再试试。
